# Generated by Django 2.1.2 on 2018-10-19 03:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosharing', '0005_auto_20181019_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/ryan/photosharing_app/photosharing_site/media'), upload_to='media/'),
        ),
    ]
