# Generated by Django 2.1.2 on 2018-10-19 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photosharing', '0005_auto_20181019_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_user', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_inviter', to='photosharing.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together={('invited', 'inviter')},
        ),
    ]
